#!/bin/bash

exec 2>&1

if path={{pkgPathFor "core/jdk8"}}; then
  export JAVA_HOME=$path
fi
if [ -z ${JAVA_HOME+x} ]; then
  echo "Cannot start without core/jdk8"
  exit 1
fi

exec {{pkgPathFor "core/bash"}}/bin/bash {{pkg.path}}/bin/money-data-server -Dconfig.file={{pkg.svc_config_path}}/application.conf -Dhttp.address={{cfg.http.listen.bind}} -Dhttp.port={{cfg.http.listen.port}}
